// CODE GENERATED BY mumbojumbo 1.1 (https://github.com/jeromer/mumbojumbo) DO NOT EDIT !!!!

package hook

import (
	"unsafe"
)

func eax() uint8{
	return uint8(unsafe.Sizeof(true))
}

// Paste your full func Get() here: